version: '3.8'

services:
  # Weather application instances
  weather-app-1:
    image: ishimwefrank/weather-globe:v1
    container_name: weather-app-web01
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - weather-network

  weather-app-2:
    image: ishimwefrank/weather-globe:v1
    container_name: weather-app-web02
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - weather-network

  # HAProxy Load Balancer
  load-balancer:
    image: haproxy:2.8-alpine
    container_name: weather-lb
    ports:
      - "8080:80"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - weather-app-1
      - weather-app-2
    restart: unless-stopped
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
